# Generated by Django 4.2.30 on 2026-07-31 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_required', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
    ]
