# Generated by Django 4.2.30 on 2026-08-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'register',
            },
        ),
    ]
