# Generated by Django 4.2.30 on 2026-08-25 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Product', '0002_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Sale')], default=0)),
                ('sale', models.IntegerField(default=0)),
                ('images', models.CharField(blank=True, max_length=2000, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('company', models.CharField(max_length=255)),
                ('id_brand', models.ForeignKey(db_column='id_brand', on_delete=django.db.models.deletion.CASCADE, to='Product.brand')),
                ('id_category', models.ForeignKey(db_column='id_category', on_delete=django.db.models.deletion.CASCADE, to='Product.category')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
