# Generated by Django 4.2.30 on 2026-08-26 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
