# Generated by Django 4.2.30 on 2026-08-18 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Blog', '0002_alter_blog_author_rate_rate_unique_blog_user_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmt', models.CharField(max_length=100)),
                ('avatar_user', models.ImageField(blank=True, null=True, upload_to='comment_avatar')),
                ('name_user', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('id_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.blog')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
        ),
    ]
