# Generated by Django 4.2.30 on 2026-08-18 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Blog.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='avatar_user',
            field=models.ImageField(blank=True, null=True, upload_to='comment_avatar/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cmt',
            field=models.TextField(),
        ),
    ]
